// Mock data for the hardware marketplace

export interface Ad {
  id: string;
  title: string;
  price: number;
  component: "GPU" | "CPU" | "RAM" | "SSD" | "Motherboard";
  model: string;
  condition: "Neuf" | "Comme neuf" | "Très bon état" | "Bon état" | "Satisfaisant";
  location: string;
  region: string;
  date: string;
  seller: "Particulier" | "Professionnel";
  dealScore: number; // 0-100
  fairValue: number;
  shipping: boolean;
  imageUrl?: string;
  priceHistory?: { date: string; price: number }[];
}

export interface Model {
  id: string;
  name: string;
  category: "GPU" | "CPU" | "RAM" | "SSD" | "Motherboard";
  brand: string;
  medianPrice: number;
  priceChange7d: number;
  priceChange30d: number;
  volume: number;
  rarity: "Commun" | "Peu courant" | "Rare" | "Très rare";
  lastUpdate: string;
  priceHistory: { date: string; price: number }[];
}

export interface MarketStats {
  totalAds: number;
  opportunities: number;
  medianGPUPrice: number;
  totalVolume: number;
}

// Mock Ads
export const mockAds: Ad[] = [
  {
    id: "1",
    title: "RTX 4060 Ti 8GB MSI Gaming X",
    price: 320,
    component: "GPU",
    model: "RTX 4060 Ti",
    condition: "Comme neuf",
    location: "Paris 15e",
    region: "Île-de-France",
    date: "2025-01-15",
    seller: "Particulier",
    dealScore: 92,
    fairValue: 380,
    shipping: true,
    priceHistory: [
      { date: "2025-01-01", price: 350 },
      { date: "2025-01-08", price: 335 },
      { date: "2025-01-15", price: 320 },
    ],
  },
  {
    id: "2",
    title: "AMD Ryzen 7 7800X3D",
    price: 380,
    component: "CPU",
    model: "Ryzen 7 7800X3D",
    condition: "Neuf",
    location: "Lyon 3e",
    region: "Auvergne-Rhône-Alpes",
    date: "2025-01-14",
    seller: "Professionnel",
    dealScore: 85,
    fairValue: 430,
    shipping: true,
  },
  {
    id: "3",
    title: "Corsair Vengeance DDR5 32GB (2x16GB) 6000MHz",
    price: 110,
    component: "RAM",
    model: "DDR5 32GB 6000MHz",
    condition: "Très bon état",
    location: "Marseille",
    region: "Provence-Alpes-Côte d'Azur",
    date: "2025-01-13",
    seller: "Particulier",
    dealScore: 78,
    fairValue: 130,
    shipping: false,
  },
  {
    id: "4",
    title: "RTX 3080 10GB ASUS TUF",
    price: 450,
    component: "GPU",
    model: "RTX 3080",
    condition: "Bon état",
    location: "Toulouse",
    region: "Occitanie",
    date: "2025-01-12",
    seller: "Particulier",
    dealScore: 88,
    fairValue: 520,
    shipping: true,
  },
  {
    id: "5",
    title: "Samsung 980 Pro 2TB NVMe",
    price: 140,
    component: "SSD",
    model: "980 Pro 2TB",
    condition: "Comme neuf",
    location: "Bordeaux",
    region: "Nouvelle-Aquitaine",
    date: "2025-01-11",
    seller: "Particulier",
    dealScore: 91,
    fairValue: 170,
    shipping: true,
  },
  {
    id: "6",
    title: "RTX 4090 24GB Gigabyte Gaming OC",
    price: 1650,
    component: "GPU",
    model: "RTX 4090",
    condition: "Neuf",
    location: "Nice",
    region: "Provence-Alpes-Côte d'Azur",
    date: "2025-01-15",
    seller: "Professionnel",
    dealScore: 88,
    fairValue: 1850,
    shipping: true,
  },
  {
    id: "7",
    title: "Intel Core i9-13900K",
    price: 520,
    component: "CPU",
    model: "i9-13900K",
    condition: "Très bon état",
    location: "Nantes",
    region: "Pays de la Loire",
    date: "2025-01-14",
    seller: "Particulier",
    dealScore: 65,
    fairValue: 580,
    shipping: false,
  },
  {
    id: "8",
    title: "G.Skill Trident Z5 RGB 64GB DDR5 7200MHz",
    price: 280,
    component: "RAM",
    model: "DDR5 64GB 7200MHz",
    condition: "Neuf",
    location: "Strasbourg",
    region: "Grand Est",
    date: "2025-01-13",
    seller: "Professionnel",
    dealScore: 82,
    fairValue: 330,
    shipping: true,
  },
  {
    id: "9",
    title: "WD Black SN850X 1TB",
    price: 95,
    component: "SSD",
    model: "SN850X 1TB",
    condition: "Bon état",
    location: "Lille",
    region: "Hauts-de-France",
    date: "2025-01-12",
    seller: "Particulier",
    dealScore: 75,
    fairValue: 115,
    shipping: true,
  },
  {
    id: "10",
    title: "ASUS ROG Strix Z790-E Gaming",
    price: 380,
    component: "Motherboard",
    model: "Z790-E",
    condition: "Comme neuf",
    location: "Rennes",
    region: "Bretagne",
    date: "2025-01-11",
    seller: "Particulier",
    dealScore: 89,
    fairValue: 450,
    shipping: true,
  },
  {
    id: "11",
    title: "RTX 3060 12GB MSI Ventus",
    price: 280,
    component: "GPU",
    model: "RTX 3060",
    condition: "Bon état",
    location: "Montpellier",
    region: "Occitanie",
    date: "2025-01-10",
    seller: "Particulier",
    dealScore: 72,
    fairValue: 320,
    shipping: false,
  },
  {
    id: "12",
    title: "AMD Ryzen 5 5600X",
    price: 140,
    component: "CPU",
    model: "Ryzen 5 5600X",
    condition: "Très bon état",
    location: "Grenoble",
    region: "Auvergne-Rhône-Alpes",
    date: "2025-01-09",
    seller: "Particulier",
    dealScore: 85,
    fairValue: 170,
    shipping: true,
  },
  {
    id: "13",
    title: "Crucial P3 Plus 4TB NVMe",
    price: 220,
    component: "SSD",
    model: "P3 Plus 4TB",
    condition: "Neuf",
    location: "Dijon",
    region: "Bourgogne-Franche-Comté",
    date: "2025-01-08",
    seller: "Professionnel",
    dealScore: 90,
    fairValue: 270,
    shipping: true,
  },
  {
    id: "14",
    title: "Kingston Fury Beast 16GB DDR4 3200MHz",
    price: 45,
    component: "RAM",
    model: "DDR4 16GB 3200MHz",
    condition: "Satisfaisant",
    location: "Toulon",
    region: "Provence-Alpes-Côte d'Azur",
    date: "2025-01-07",
    seller: "Particulier",
    dealScore: 58,
    fairValue: 55,
    shipping: false,
  },
  {
    id: "15",
    title: "MSI MAG B650 Tomahawk WiFi",
    price: 180,
    component: "Motherboard",
    model: "B650 Tomahawk",
    condition: "Neuf",
    location: "Angers",
    region: "Pays de la Loire",
    date: "2025-01-06",
    seller: "Professionnel",
    dealScore: 87,
    fairValue: 220,
    shipping: true,
  },
  {
    id: "16",
    title: "RX 7900 XTX 24GB Sapphire Nitro+",
    price: 950,
    component: "GPU",
    model: "RX 7900 XTX",
    condition: "Comme neuf",
    location: "Clermont-Ferrand",
    region: "Auvergne-Rhône-Alpes",
    date: "2025-01-05",
    seller: "Particulier",
    dealScore: 93,
    fairValue: 1100,
    shipping: true,
  },
  {
    id: "17",
    title: "Intel Core i5-12400F",
    price: 130,
    component: "CPU",
    model: "i5-12400F",
    condition: "Bon état",
    location: "Le Havre",
    region: "Normandie",
    date: "2025-01-04",
    seller: "Particulier",
    dealScore: 68,
    fairValue: 150,
    shipping: false,
  },
  {
    id: "18",
    title: "TeamGroup T-Force Vulcan 32GB DDR4 3600MHz",
    price: 70,
    component: "RAM",
    model: "DDR4 32GB 3600MHz",
    condition: "Très bon état",
    location: "Reims",
    region: "Grand Est",
    date: "2025-01-03",
    seller: "Particulier",
    dealScore: 81,
    fairValue: 90,
    shipping: true,
  },
  {
    id: "19",
    title: "Seagate FireCuda 530 2TB",
    price: 185,
    component: "SSD",
    model: "FireCuda 530 2TB",
    condition: "Neuf",
    location: "Tours",
    region: "Centre-Val de Loire",
    date: "2025-01-02",
    seller: "Professionnel",
    dealScore: 76,
    fairValue: 220,
    shipping: true,
  },
  {
    id: "20",
    title: "Gigabyte B550 AORUS Elite V2",
    price: 110,
    component: "Motherboard",
    model: "B550 AORUS Elite",
    condition: "Bon état",
    location: "Orléans",
    region: "Centre-Val de Loire",
    date: "2025-01-01",
    seller: "Particulier",
    dealScore: 70,
    fairValue: 135,
    shipping: false,
  },
  {
    id: "21",
    title: "RTX 4070 Ti 12GB EVGA FTW3",
    price: 680,
    component: "GPU",
    model: "RTX 4070 Ti",
    condition: "Neuf",
    location: "Brest",
    region: "Bretagne",
    date: "2024-12-31",
    seller: "Professionnel",
    dealScore: 84,
    fairValue: 800,
    shipping: true,
  },
  {
    id: "22",
    title: "AMD Ryzen 9 7950X",
    price: 580,
    component: "CPU",
    model: "Ryzen 9 7950X",
    condition: "Comme neuf",
    location: "Besançon",
    region: "Bourgogne-Franche-Comté",
    date: "2024-12-30",
    seller: "Particulier",
    dealScore: 79,
    fairValue: 680,
    shipping: true,
  },
  {
    id: "23",
    title: "Corsair Vengeance RGB Pro 16GB DDR4 3600MHz",
    price: 52,
    component: "RAM",
    model: "DDR4 16GB 3600MHz",
    condition: "Satisfaisant",
    location: "Caen",
    region: "Normandie",
    date: "2024-12-29",
    seller: "Particulier",
    dealScore: 55,
    fairValue: 60,
    shipping: false,
  },
  {
    id: "24",
    title: "Kingston KC3000 2TB NVMe",
    price: 165,
    component: "SSD",
    model: "KC3000 2TB",
    condition: "Très bon état",
    location: "Limoges",
    region: "Nouvelle-Aquitaine",
    date: "2024-12-28",
    seller: "Particulier",
    dealScore: 83,
    fairValue: 200,
    shipping: true,
  },
  {
    id: "25",
    title: "ASUS TUF Gaming X670E-Plus",
    price: 250,
    component: "Motherboard",
    model: "X670E-Plus",
    condition: "Neuf",
    location: "Perpignan",
    region: "Occitanie",
    date: "2024-12-27",
    seller: "Professionnel",
    dealScore: 86,
    fairValue: 300,
    shipping: true,
  },
  {
    id: "26",
    title: "GTX 1660 Super 6GB Zotac",
    price: 180,
    component: "GPU",
    model: "GTX 1660 Super",
    condition: "Bon état",
    location: "Amiens",
    region: "Hauts-de-France",
    date: "2024-12-26",
    seller: "Particulier",
    dealScore: 42,
    fairValue: 160,
    shipping: false,
  },
  {
    id: "27",
    title: "Intel Core i7-12700K",
    price: 320,
    component: "CPU",
    model: "i7-12700K",
    condition: "Comme neuf",
    location: "Metz",
    region: "Grand Est",
    date: "2024-12-25",
    seller: "Particulier",
    dealScore: 73,
    fairValue: 380,
    shipping: true,
  },
  {
    id: "28",
    title: "G.Skill Ripjaws V 64GB DDR4 3200MHz",
    price: 140,
    component: "RAM",
    model: "DDR4 64GB 3200MHz",
    condition: "Très bon état",
    location: "Nancy",
    region: "Grand Est",
    date: "2024-12-24",
    seller: "Particulier",
    dealScore: 80,
    fairValue: 175,
    shipping: true,
  },
  {
    id: "29",
    title: "Crucial MX500 1TB SATA",
    price: 65,
    component: "SSD",
    model: "MX500 1TB",
    condition: "Bon état",
    location: "Poitiers",
    region: "Nouvelle-Aquitaine",
    date: "2024-12-23",
    seller: "Particulier",
    dealScore: 60,
    fairValue: 75,
    shipping: false,
  },
  {
    id: "30",
    title: "ASRock B760M Pro RS",
    price: 95,
    component: "Motherboard",
    model: "B760M Pro",
    condition: "Neuf",
    location: "Ajaccio",
    region: "Corse",
    date: "2024-12-22",
    seller: "Professionnel",
    dealScore: 77,
    fairValue: 120,
    shipping: true,
  },
  {
    id: "31",
    title: "RX 6700 XT 12GB PowerColor Red Devil",
    price: 320,
    component: "GPU",
    model: "RX 6700 XT",
    condition: "Très bon état",
    location: "Mulhouse",
    region: "Grand Est",
    date: "2024-12-21",
    seller: "Particulier",
    dealScore: 87,
    fairValue: 390,
    shipping: true,
  },
  {
    id: "32",
    title: "AMD Ryzen 5 7600",
    price: 190,
    component: "CPU",
    model: "Ryzen 5 7600",
    condition: "Neuf",
    location: "Avignon",
    region: "Provence-Alpes-Côte d'Azur",
    date: "2024-12-20",
    seller: "Professionnel",
    dealScore: 81,
    fairValue: 230,
    shipping: true,
  },
  {
    id: "33",
    title: "Corsair Dominator Platinum RGB 32GB DDR5 5600MHz",
    price: 195,
    component: "RAM",
    model: "DDR5 32GB 5600MHz",
    condition: "Comme neuf",
    location: "La Rochelle",
    region: "Nouvelle-Aquitaine",
    date: "2024-12-19",
    seller: "Particulier",
    dealScore: 74,
    fairValue: 240,
    shipping: false,
  },
  {
    id: "34",
    title: "Samsung 870 EVO 500GB SATA",
    price: 45,
    component: "SSD",
    model: "870 EVO 500GB",
    condition: "Satisfaisant",
    location: "Valence",
    region: "Auvergne-Rhône-Alpes",
    date: "2024-12-18",
    seller: "Particulier",
    dealScore: 52,
    fairValue: 50,
    shipping: false,
  },
  {
    id: "35",
    title: "MSI MPG Z690 Carbon WiFi",
    price: 280,
    component: "Motherboard",
    model: "Z690 Carbon",
    condition: "Très bon état",
    location: "Saint-Étienne",
    region: "Auvergne-Rhône-Alpes",
    date: "2024-12-17",
    seller: "Particulier",
    dealScore: 85,
    fairValue: 340,
    shipping: true,
  },
  {
    id: "36",
    title: "RTX 3070 8GB ASUS Dual",
    price: 380,
    component: "GPU",
    model: "RTX 3070",
    condition: "Bon état",
    location: "Dunkerque",
    region: "Hauts-de-France",
    date: "2024-12-16",
    seller: "Particulier",
    dealScore: 78,
    fairValue: 450,
    shipping: true,
  },
  {
    id: "37",
    title: "Intel Core i3-12100F",
    price: 85,
    component: "CPU",
    model: "i3-12100F",
    condition: "Neuf",
    location: "Pau",
    region: "Nouvelle-Aquitaine",
    date: "2024-12-15",
    seller: "Professionnel",
    dealScore: 71,
    fairValue: 105,
    shipping: true,
  },
  {
    id: "38",
    title: "Patriot Viper Steel 16GB DDR4 4400MHz",
    price: 62,
    component: "RAM",
    model: "DDR4 16GB 4400MHz",
    condition: "Comme neuf",
    location: "Bayonne",
    region: "Nouvelle-Aquitaine",
    date: "2024-12-14",
    seller: "Particulier",
    dealScore: 66,
    fairValue: 80,
    shipping: false,
  },
  {
    id: "39",
    title: "Sabrent Rocket 4 Plus 1TB",
    price: 105,
    component: "SSD",
    model: "Rocket 4 Plus 1TB",
    condition: "Neuf",
    location: "Cannes",
    region: "Provence-Alpes-Côte d'Azur",
    date: "2024-12-13",
    seller: "Professionnel",
    dealScore: 89,
    fairValue: 135,
    shipping: true,
  },
  {
    id: "40",
    title: "Gigabyte X570 AORUS Master",
    price: 220,
    component: "Motherboard",
    model: "X570 AORUS Master",
    condition: "Bon état",
    location: "Annecy",
    region: "Auvergne-Rhône-Alpes",
    date: "2024-12-12",
    seller: "Particulier",
    dealScore: 63,
    fairValue: 250,
    shipping: false,
  },
  {
    id: "41",
    title: "RX 7800 XT 16GB XFX Speedster MERC",
    price: 520,
    component: "GPU",
    model: "RX 7800 XT",
    condition: "Neuf",
    location: "Chambéry",
    region: "Auvergne-Rhône-Alpes",
    date: "2024-12-11",
    seller: "Professionnel",
    dealScore: 91,
    fairValue: 620,
    shipping: true,
  },
  {
    id: "42",
    title: "AMD Ryzen 9 5900X",
    price: 280,
    component: "CPU",
    model: "Ryzen 9 5900X",
    condition: "Très bon état",
    location: "Troyes",
    region: "Grand Est",
    date: "2024-12-10",
    seller: "Particulier",
    dealScore: 82,
    fairValue: 340,
    shipping: true,
  },
  {
    id: "43",
    title: "ADATA XPG Spectrix D60G 32GB DDR4 3600MHz",
    price: 88,
    component: "RAM",
    model: "DDR4 32GB 3600MHz",
    condition: "Bon état",
    location: "Bourges",
    region: "Centre-Val de Loire",
    date: "2024-12-09",
    seller: "Particulier",
    dealScore: 75,
    fairValue: 110,
    shipping: false,
  },
  {
    id: "44",
    title: "WD Blue SN570 250GB NVMe",
    price: 28,
    component: "SSD",
    model: "SN570 250GB",
    condition: "Satisfaisant",
    location: "Chartres",
    region: "Centre-Val de Loire",
    date: "2024-12-08",
    seller: "Particulier",
    dealScore: 48,
    fairValue: 30,
    shipping: false,
  },
  {
    id: "45",
    title: "ASUS Prime H610M-A D4",
    price: 72,
    component: "Motherboard",
    model: "H610M-A",
    condition: "Neuf",
    location: "Lorient",
    region: "Bretagne",
    date: "2024-12-07",
    seller: "Professionnel",
    dealScore: 69,
    fairValue: 90,
    shipping: true,
  },
];

// Mock Models
export const mockModels: Model[] = [
  {
    id: "1",
    name: "RTX 4060 Ti 8GB",
    category: "GPU",
    brand: "NVIDIA",
    medianPrice: 380,
    priceChange7d: -5.2,
    priceChange30d: -8.1,
    volume: 245,
    rarity: "Commun",
    lastUpdate: "2025-01-15",
    priceHistory: [
      { date: "2024-12-15", price: 410 },
      { date: "2024-12-22", price: 405 },
      { date: "2024-12-29", price: 395 },
      { date: "2025-01-05", price: 390 },
      { date: "2025-01-12", price: 380 },
    ],
  },
  {
    id: "2",
    name: "RTX 3080 10GB",
    category: "GPU",
    brand: "NVIDIA",
    medianPrice: 520,
    priceChange7d: -2.8,
    priceChange30d: -12.5,
    volume: 180,
    rarity: "Peu courant",
    lastUpdate: "2025-01-14",
    priceHistory: [
      { date: "2024-12-15", price: 590 },
      { date: "2024-12-22", price: 570 },
      { date: "2024-12-29", price: 550 },
      { date: "2025-01-05", price: 535 },
      { date: "2025-01-12", price: 520 },
    ],
  },
  {
    id: "3",
    name: "Ryzen 7 7800X3D",
    category: "CPU",
    brand: "AMD",
    medianPrice: 430,
    priceChange7d: +1.2,
    priceChange30d: -3.4,
    volume: 89,
    rarity: "Peu courant",
    lastUpdate: "2025-01-13",
    priceHistory: [
      { date: "2024-12-15", price: 445 },
      { date: "2024-12-22", price: 440 },
      { date: "2024-12-29", price: 435 },
      { date: "2025-01-05", price: 425 },
      { date: "2025-01-12", price: 430 },
    ],
  },
  {
    id: "4",
    name: "DDR5 32GB 6000MHz",
    category: "RAM",
    brand: "Corsair",
    medianPrice: 130,
    priceChange7d: -4.5,
    priceChange30d: -9.8,
    volume: 320,
    rarity: "Commun",
    lastUpdate: "2025-01-15",
    priceHistory: [
      { date: "2024-12-15", price: 145 },
      { date: "2024-12-22", price: 140 },
      { date: "2024-12-29", price: 135 },
      { date: "2025-01-05", price: 132 },
      { date: "2025-01-12", price: 130 },
    ],
  },
  {
    id: "5",
    name: "Samsung 980 Pro 2TB",
    category: "SSD",
    brand: "Samsung",
    medianPrice: 170,
    priceChange7d: -1.8,
    priceChange30d: -6.2,
    volume: 156,
    rarity: "Commun",
    lastUpdate: "2025-01-14",
    priceHistory: [
      { date: "2024-12-15", price: 182 },
      { date: "2024-12-22", price: 178 },
      { date: "2024-12-29", price: 174 },
      { date: "2025-01-05", price: 172 },
      { date: "2025-01-12", price: 170 },
    ],
  },
];

export const mockStats: MarketStats = {
  totalAds: 12547,
  opportunities: 342,
  medianGPUPrice: 385,
  totalVolume: 1847230,
};

export const subscriptionPlans = [
  {
    name: "Free",
    price: 0,
    credits: 20,
    features: [
      "20 crédits/mois",
      "Market Score gratuit",
      "Catalogue complet",
      "Introduction plateforme",
    ],
  },
  {
    name: "Standard",
    price: 11.99,
    credits: 200,
    features: [
      "200 crédits/mois",
      "Estimator complet",
      "10 alertes actives",
      "Formation avancée",
      "Tendances marché",
    ],
    popular: true,
  },
  {
    name: "Pro",
    price: 24.99,
    credits: 800,
    features: [
      "800 crédits/mois",
      "Scénarios comparatifs",
      "100 alertes + watchlist illimitée",
      "Export données",
      "Support prioritaire",
      "Historique étendu",
    ],
  },
];
