// Re-export from provider-based hooks for backward compatibility
export {
  useTrends,
  useTrainingData,
  useCompleteModule,
  useDeals,
  useMarketSummary,
  useCategories,
  useBrands,
  useFamilies,
  useCatalogModels,
  useCatalogSummary,
  useAddModelToWatchlist,
  useModelDetail,
  useModelPriceHistory,
  useModelAds,
  useToggleModelWatchlist,
  useCreatePriceAlert,
  useAdDetail,
  useAdPriceHistory,
  useAddAdToWatchlist,
  useCreateAdAlert,
  useModelsAutocomplete,
  useRunEstimation,
  useEstimationHistory,
  useEstimatorStats,
  useAvailableTasks,
  useMyTasks,
  useClaimTask,
  useCommunityStats,
  useLeaderboard,
  useStartScrap,
  useJobStatus,
  useCancelJob,
  useUserJobs,
  useUserCredits,
} from "./useProviderData";

// Entitlements - single source of truth for user permissions
export {
  useEntitlements,
  useCanCreateAlert,
  useCanScrap,
  useCanAddToWatchlist,
  useCanExport,
  type PlanType,
  type ScrapType,
  type PlanLimits,
  type Entitlements,
} from "./useEntitlements";
